export default {
  360000236288: {
    label: 'Viz - Vimeo Brand',
    categories: [
      { label: 'Account', value: 'account' },
      { label: 'Billing + Membership', value: 'billing' },
      { label: 'Video Settings', value: 'video_settings' },
      { label: 'General Site', value: 'general_site' },
      { label: 'Collections', value: 'collections' },
      { label: 'Live', value: 'live' },
      { label: 'Mobile + Apps', value: 'mobile_apps' },
      { label: 'API / Developer / Backend', value: 'api_developer' },
      { label: 'Player / Playback', value: 'player_playback' },
      { label: 'Uploading / Conversion', value: 'uploading_conversion' },
      { label: 'VOD Buyer', value: 'vod_buyer' },
      { label: 'VOD Seller', value: 'vod_seller' },
      { label: 'Stats', value: 'stats' },
      { label: 'Other', value: 'other' },
      { label: 'Trust & Safety', value: 'trust_safety' },
    ],
  },
  27056858: {
    label: 'Trust & Safety',
    categories: [
      { label: 'Other', value: 'other' },
      { label: 'Trust & Safety', value: 'trust_safety' },
    ],
  },
  360000231548: {
    label: 'Livestream All Support',
    categories: [
      { label: 'Livestream Account', value: 'livestream_account' },
      { label: 'Livestream Billing + Membership', value: 'livestream_billing_membership' },
      { label: 'Viewing Streams', value: 'viewing_streams' },
      { label: 'Studio', value: 'studio' },
      { label: 'Third Party', value: 'third_party' },
      { label: 'Shipping', value: 'shipping' },
      { label: 'Broadcaster', value: 'broadcaster' },
      { label: 'Mevo', value: 'mevo' },
      { label: 'Livestream Producer', value: 'livestream_producer' },
      { label: 'Livestream Platform Features', value: 'livestream_platform_features' },
      { label: 'Livestream Production / Streaming', value: 'livestream_production_streaming' },
      { label: 'RMA', value: 'rma' },
      { label: 'Livestream Legal', value: 'livestream_legal' },
      { label: 'Other', value: 'other' },
    ],
  },
};
